// Per-game Etsy listing data for selling each of the 15 games as its own product.
// Keyed by game number (same order as build.mjs). All buyer-facing copy is English.

export const GAMES_META = {
  1: {
    slug: 'spooky-picture-bingo', name: 'Spooky Picture Bingo', icon: 'Ghost', price: '3.99',
    hook: 'Halloween bingo that even little ones who can\'t read yet can play: every square has a picture AND a word.',
    includes: ['30 unique bingo cards (2 per page)', 'Picture + word on every square', 'Caller tiles to cut out', '5 ways to win: line, four corners, letter X, blackout'],
    title: 'Halloween Picture Bingo, 30 Printable Bingo Cards for Kids, Preschool Classroom Party Game, Spooky Bingo with Pictures, Instant Download',
    tags: ['halloween bingo', 'picture bingo', 'bingo cards', 'kids bingo game', 'preschool halloween', 'classroom party', 'toddler activity', 'halloween kids game', 'printable bingo', 'bingo for kids', 'halloween party game', 'class party game', 'spooky bingo'],
  },
  2: {
    slug: 'halloween-trivia', name: 'Halloween Trivia', icon: 'Crystal Ball', price: '2.99',
    hook: 'Two rounds of Halloween trivia: an easy Kids Round and a tricky Grown-Ups Round.',
    includes: ['Kids Round: 15 questions', 'Grown-Ups Round: 15 questions', 'Team answer sheets', 'Answer key'],
    title: 'Halloween Trivia Game, Printable Quiz for Kids and Adults, 30 Questions with Answer Key, Office Party, Classroom, Family Game Night',
    tags: ['halloween trivia', 'trivia game', 'halloween quiz', 'printable trivia', 'office party game', 'kids trivia', 'adult party game', 'family game night', 'classroom game', 'trivia questions', 'halloween games', 'team building game', 'party quiz'],
  },
  3: {
    slug: 'would-you-rather', name: 'Would You Rather? Halloween Edition', icon: 'Witch Hat', price: '2.49',
    hook: '36 spooky, silly "Would you rather" questions that get everyone talking and laughing.',
    includes: ['36 question cards (12 per page)', 'Left/right room game rules', 'Family-friendly questions'],
    title: 'Halloween Would You Rather Cards, 36 Printable Question Cards for Kids and Family, Halloween Party Game, Classroom Activity, Digital PDF',
    tags: ['would you rather', 'halloween game', 'conversation cards', 'kids party game', 'family game night', 'classroom activity', 'icebreaker game', 'printable cards', 'halloween party', 'kids printable', 'question game', 'brain break', 'morning meeting'],
  },
  4: {
    slug: 'monster-charades', name: 'Monster Charades', icon: 'Mask', price: '2.99',
    hook: '36 act-it-out cards, from easy kid cards to hilarious grown-up ones like "Zombie at the dentist".',
    includes: ['36 charades cards (18 per page)', 'Easy Kids cards + funny Teens/Adults cards', 'Team scoreboard'],
    title: 'Halloween Charades Game, 36 Printable Act It Out Cards for Kids and Adults, Monster Party Game, Family Game Night, Instant Download',
    tags: ['halloween charades', 'charades cards', 'charades game', 'act it out game', 'kids party game', 'adult party game', 'family game night', 'halloween games', 'printable cards', 'party game cards', 'office party game', 'classroom game', 'monster party'],
  },
  5: {
    slug: 'spooky-categories', name: 'Spooky Categories', icon: 'Potion', price: '2.49',
    hook: 'The fast "think of a word" game with a Halloween twist. Pick a letter, start the timer, go!',
    includes: ['Player sheet with 12 Halloween categories', '3 rounds per sheet', 'Letter strip to cut out'],
    title: 'Halloween Categories Game, Printable Word Game for Teens and Adults, Think Fast Party Game, Office Party, Game Night, Instant Download',
    tags: ['halloween game', 'categories game', 'word game', 'teen party game', 'adult party game', 'office party game', 'game night', 'printable game', 'halloween party', 'party word game', 'think fast game', 'group game', 'fall party game'],
  },
  6: {
    slug: 'monster-word-scramble', name: 'Monster Word Scramble', icon: 'Spider', price: '1.99',
    hook: '20 jumbled Halloween words to unscramble: a perfect quiet activity for parties and classrooms.',
    includes: ['20 scrambled Halloween words', 'Answer key'],
    title: 'Halloween Word Scramble, Printable Unscramble Worksheet with Answer Key, Kids Classroom Activity, Halloween Party Game, Instant Download',
    tags: ['word scramble', 'halloween worksheet', 'unscramble words', 'classroom activity', 'kids activity', 'halloween printable', 'word puzzle', 'kids worksheet', 'early finisher', 'halloween game', 'spelling activity', 'homeschool', 'quiet time activity'],
  },
  7: {
    slug: 'haunted-word-search', name: 'Haunted Word Search', icon: 'Owl', price: '1.99',
    hook: 'Two Halloween word searches: an easy one for little monsters and a hard one with words in all 8 directions.',
    includes: ['Level 1: easy 9x9 puzzle (big letters)', 'Level 2: hard 15x15 puzzle', 'Answer keys for both'],
    title: 'Halloween Word Search, 2 Printable Puzzles Easy and Hard with Answer Keys, Kids Activity Sheet, Classroom Halloween Party, Instant Download',
    tags: ['word search', 'halloween puzzle', 'word find', 'puzzle for kids', 'kids activity', 'classroom activity', 'halloween printable', 'activity sheet', 'early finisher', 'word puzzle', 'homeschool', 'quiet time activity', 'halloween games'],
  },
  8: {
    slug: 'pumpkin-draw-and-guess', name: 'Pumpkin Draw & Guess', icon: 'Pumpkin', price: '2.49',
    hook: 'Draw it, guess it, laugh about it! 40 Halloween drawing cards in an easy and a hard deck.',
    includes: ['20 easy cards (1 point)', '20 hard cards (2 points)', 'Team scoreboard'],
    title: 'Halloween Drawing Game, 40 Printable Draw and Guess Cards, Easy and Hard Party Game for Kids and Adults, Family Game Night, Instant Download',
    tags: ['drawing game', 'draw and guess', 'halloween game', 'party game cards', 'kids party game', 'family game night', 'guessing game', 'printable game', 'classroom game', 'adult party game', 'halloween party', 'game night', 'team game'],
  },
  9: {
    slug: 'spooky-story-fill-ins', name: 'Spooky Story Fill-ins', icon: 'Candle', price: '1.99',
    hook: 'Collect silly words from your friends, then read the spooky story out loud. Guaranteed giggles.',
    includes: ['2 fill-in-the-blank Halloween stories', '12 word prompts per story (noun, verb, adjective...)'],
    title: 'Halloween Fill in the Blank Stories, 2 Printable Funny Word Games for Kids, Halloween Party Activity, Classroom Game, Instant Download',
    tags: ['fill in the blank', 'funny story game', 'word game', 'kids activity', 'halloween printable', 'classroom activity', 'parts of speech', 'grammar game', 'kids party game', 'silly stories', 'halloween game', 'homeschool', 'road trip game'],
  },
  10: {
    slug: 'who-am-i', name: 'Who Am I? Guessing Cards', icon: 'Black Cat', price: '2.49',
    hook: 'Tape a card on each guest\'s back. Ask yes/no questions. Who will guess their Halloween character first?',
    includes: ['24 guessing cards with pictures (12 per page)', 'Yes/no question rules'],
    title: 'Halloween Who Am I Game, 24 Printable Guessing Cards, Headband Style Party Game for Kids and Adults, Icebreaker, Instant Download',
    tags: ['who am i game', 'guessing game', 'headband game', 'halloween game', 'icebreaker game', 'kids party game', 'party game cards', 'family game night', 'classroom game', 'printable game', 'halloween party', 'adult party game', 'forehead game'],
  },
  11: {
    slug: 'this-or-that', name: 'This or That? Run-Around Game', icon: 'Moon', price: '1.99',
    hook: 'Zero-prep warm-up game: call out two choices and everyone runs to their side of the room.',
    includes: ['20 Halloween "this or that" rounds', 'Host rules + challenge mode'],
    title: 'Halloween This or That Game, Printable Run Around Party Game, Kids Classroom Movement Activity, Brain Break, Instant Download',
    tags: ['this or that', 'halloween game', 'brain break', 'classroom game', 'movement activity', 'kids party game', 'icebreaker game', 'printable game', 'halloween party', 'kids activity', 'family game', 'group game', 'morning meeting'],
  },
  12: {
    slug: 'two-truths-and-a-spooky-lie', name: 'Two Truths & a Spooky Lie', icon: 'Lantern', price: '1.99',
    hook: 'The classic icebreaker with a Halloween twist: perfect for office parties and grown-up get-togethers.',
    includes: ['6 player cards per page (print as many as you need)', 'Prompt ideas on every card', 'Scoring rules'],
    title: 'Halloween Two Truths and a Lie, Printable Icebreaker Game for Adults and Teens, Office Party Team Building, Instant Download',
    tags: ['two truths a lie', 'icebreaker game', 'office party game', 'team building', 'adult party game', 'teen party game', 'halloween game', 'getting to know you', 'work party game', 'printable game', 'halloween party', 'coworker game', 'staff party'],
  },
  13: {
    slug: 'roll-a-monster', name: 'Roll a Monster', icon: 'Eyeball', price: '1.99',
    hook: 'Roll a die six times and draw the silly monster the dice create. No two monsters are ever the same!',
    includes: ['Dice chart: body, eyes, mouth, arms, legs, extras', 'Big drawing frame on the same page'],
    title: 'Roll a Monster Drawing Game, Halloween Dice Game for Kids, Printable Classroom Art Activity, Halloween Party, Instant Download',
    tags: ['roll a monster', 'dice game', 'drawing game', 'kids art activity', 'halloween activity', 'classroom activity', 'monster drawing', 'kids printable', 'halloween party', 'art lesson', 'preschool activity', 'rainy day activity', 'homeschool art'],
  },
  14: {
    slug: 'guess-the-candy-jar', name: 'Guess the Candy Jar', icon: 'Candy Bucket', price: '1.99',
    hook: 'Fill a jar with candy, put out the sign and let guests guess. Closest guess wins the jar!',
    includes: ['"How many candies?" sign', '10 guess slips per page'],
    title: 'Guess How Many Candies in the Jar, Halloween Candy Guessing Game Sign and Slips, Printable Party Game, Office Classroom, Instant Download',
    tags: ['candy jar game', 'guessing game', 'candy guess', 'halloween game', 'party sign', 'office party game', 'classroom party', 'kids party game', 'printable sign', 'halloween party', 'guess the candy', 'fall festival', 'school carnival'],
  },
  15: {
    slug: 'costume-contest-awards', name: 'Costume Contest Ballots & Awards', icon: 'Star', price: '2.99',
    hook: 'Everything for a Halloween costume contest: voting ballots plus 6 award certificates for the winners.',
    includes: ['8 voting ballots per page', '6 award certificates: Scariest, Funniest, Most Creative, Best Group, Best DIY, Best Pumpkin'],
    title: 'Halloween Costume Contest Ballots and Award Certificates, Printable Voting Cards, 6 Costume Awards, Office and Kids Party, Digital PDF',
    tags: ['costume contest', 'costume ballot', 'voting ballot', 'award certificate', 'halloween awards', 'costume awards', 'office party', 'kids party', 'halloween printable', 'best costume award', 'party voting', 'halloween party', 'costume party'],
  },
};
